def make(data, vis_params):
    uuid = vis_params['id']

    # first pass at axis control
    data_string = ','.join(str(d[vis_params['x']]) for d in data)

    js_template = (
        "var data = [" + data_string + "];"
        ""
        "requirejs(['nbextensions/d3.min'], function(d3) {"
        ""
        "if (document.getElementById('" + uuid + "') === null)"
        "    element.append($('<div/>', {id:'" + uuid + "'}));"
        ""
        "var formatCount = d3.format(',.0f');"
        ""
        "var svg = d3.select('#" + uuid + "')"
        "    .append('svg')"
        "        .attr('viewBox', '0 0 960 480')"
        "        .attr('width', 960)"
        "        .attr('height', 480);"
        ""
        "var mgn = {top:20, right:0, bottom:20, left:0},"
        "    wdt = svg.attr('width') - mgn.left - mgn.right,"
        "    hgt = svg.attr('height') - mgn.top - mgn.bottom,"
        "    g = svg.append('g')"
        "        .attr('transform', 'translate('+mgn.left+','+mgn.top+')');"
        ""
        "    var histogram = d3.histogram()(data);"
        "    var xScale = d3.scaleLinear().rangeRound([0, wdt])"
        "        .domain([d3.min(data, function(d) { return d; }),"
        "            d3.max(data, function(d) { return d; })])"
        "        .range([mgn.left, wdt]);"
        ""
        "    var xAxis = d3.axisBottom(xScale);"
        ""
        "    var yScale = d3.scaleLinear()"
        "        .domain([0, d3.max(histogram, function(d) { return d.length; })])"
        "        .range([hgt, 0]);"
        ""
        "    var bar = g.selectAll('.bar')"
        "        .data(histogram)"
        "        .enter().append('g')"
        "        .attr('class', 'bar')"
        "        .attr('transform', function(d) {"
        "            return 'translate('+xScale(d.x0)+','+yScale(d.length)+')';"
        "    });"
        ""
        "    bar.append('rect')"
        "       .attr('width', wdt / histogram.length)"
        "       .attr('height', function(d) { return hgt - yScale(d.length); });"
        ""
        "    bar.append('text')"
        "       .attr('dy', '.75em')"
        "       .attr('y', -10)"
        "       .attr('x', wdt / histogram.length / 2)"
        "       .attr('text-anchor', 'middle')"
        "       .text(function(d) { return formatCount(d.length); });"
        ""
        "    g.append('g')"
        "     .attr('class', 'axis axis--x')"
        "     .attr('transform', 'translate(0,'+hgt+')')"
        "     .call(xAxis);"
        "});"
    )

    return ' '.join(js_template.split())