def make(data, vis_params):
    uuid = vis_params['id']

    # first pass at axis control
    data_string = ','.join(str(d[vis_params['x']]) for d in data)

    js_template = (
        "let data = [" + data_string + "];"
        ""
        "requirejs(['nbextensions/d3.min'], function(d3) {"
        ""
        "if (document.getElementById('" + uuid + "') === null)"
        "  element.append($('<div/>', {id:'" + uuid + "'}));"
        ""
        "let formatCount = d3.format(',.0f');"
        ""
        "let svg = d3.select('#" + uuid + "')"
        "    .append('svg')"
        "        .attr('viewBox', '0 0 960 480')"
        "        .attr('width', 960)"
        "        .attr('height', 480);"
        ""
        "let mgn = {top:20, right:40, bottom:20, left:40};"
        "let wdt = svg.attr('width') - mgn.left - mgn.right;"
        "let hgt = svg.attr('height') - mgn.top - mgn.bottom;"
        "let g = svg.append('g')"
        "    .attr('transform', 'translate('+mgn.left+','+mgn.top+')');"
        ""
        "let histogram = d3.histogram()(data);"
        "let xScale = d3.scaleLinear().rangeRound([0, wdt])"
        "    .domain(["
        "      d3.min(data, function(d) { return d; }),"
        "      d3.max(data, function(d) { return d; })"
        "    ])"
        "    .range([mgn.left, wdt]);"
        ""
        "let xAxis = d3.axisBottom(xScale);"
        ""
        "let yScale = d3.scaleLinear()"
        "    .domain(["
        "      0,"
        "      d3.max(histogram, function(d) { return d.length; })"
        "    ])"
        "    .range([hgt, 0]);"
        ""
        "let yAxis = d3.axisLeft(yScale);"
        ""
        "g.append('g')"
        "    .attr('class', 'axis axis--x')"
        "    .attr('transform', 'translate(0,'+hgt+')')"
        "    .call(xAxis);"
        ""
        "g.append('g')"
        "    .attr('class', 'axis axis--y')"
        "    .call(yAxis);"
        ""
        "let bar = g.selectAll('.bar')"
        "    .data(histogram)"
        "    .enter().append('g')"
        "    .attr('class', 'bar')"
        "    .attr('transform', function(d) {"
        "      return 'translate('+xScale(d.x0)+','+yScale(d.length)+')';"
        "    });"
        ""
        "bar.append('rect')"
        "    .attr('width', wdt / histogram.length)"
        "    .attr('height', function(d) { return hgt - yScale(d.length); });"
        ""
        "bar.append('text')"
        "    .attr('dy', '.75em')"
        "    .attr('y', -10)"
        "    .attr('x', wdt / histogram.length / 2)"
        "    .attr('text-anchor', 'middle')"
        "    .text(function(d) { return formatCount(d.length); });"
        "});"
    )

    return ' '.join(js_template.split())